export const CHOOSE_OPTIONS = "CHOOSE_OPTIONS";
export const ROAD_RULES = "ROAD_RULES";
export const ROAD_SURFACE_MARKINGS = "ROAD_SURFACE_MARKINGS";
export const WARNING_SIGNS = "WARNING_SIGNS";
export const HEAVY_VEHICLE_CONTROLS = "HEAVY_VEHICLE_CONTROLS";
export const LIGHT_VEHICLE_CONTROLS = "LIGHT_VEHICLE_CONTROLS";
